// SEET Mock Data — Hospitality Reputation Intelligence

export const platforms = [
  { id: "google", name: "Google Reviews", color: "#4285F4", icon: "G" },
  { id: "tripadvisor", name: "TripAdvisor", color: "#00AA6C", icon: "T" },
  { id: "booking", name: "Booking.com", color: "#003580", icon: "B" },
  { id: "agoda", name: "Agoda", color: "#5392F9", icon: "A" },
  { id: "expedia", name: "Expedia", color: "#FFB800", icon: "E" },
  { id: "talabat", name: "Talabat", color: "#FF6600", icon: "Ta" },
  { id: "elmenus", name: "Elmenus", color: "#E63946", icon: "El" },
  { id: "facebook", name: "Facebook", color: "#1877F2", icon: "F" },
  { id: "instagram", name: "Instagram", color: "#E1306C", icon: "I" },
];

export const overviewStats = {
  totalReviews: 47832,
  reviewsThisMonth: 2419,
  overallRating: 4.2,
  ratingChange: +0.3,
  sentimentScore: 78,
  sentimentChange: +5,
  responseRate: 68,
  responseRateChange: +12,
  avgResponseTime: "2.4h",
  responseTimeChange: -18,
  activeAlerts: 14,
  criticalAlerts: 3,
  pendingActions: 23,
  brandsMonitored: 6,
  propertiesMonitored: 38,
  platformsConnected: 9,
};

export const sentimentTrend = [
  { date: "Jan", positive: 71, neutral: 18, negative: 11 },
  { date: "Feb", positive: 74, neutral: 16, negative: 10 },
  { date: "Mar", positive: 69, neutral: 20, negative: 11 },
  { date: "Apr", positive: 73, neutral: 17, negative: 10 },
  { date: "May", positive: 76, neutral: 15, negative: 9 },
  { date: "Jun", positive: 75, neutral: 16, negative: 9 },
  { date: "Jul", positive: 78, neutral: 14, negative: 8 },
  { date: "Aug", positive: 80, neutral: 13, negative: 7 },
  { date: "Sep", positive: 77, neutral: 15, negative: 8 },
  { date: "Oct", positive: 79, neutral: 13, negative: 8 },
  { date: "Nov", positive: 81, neutral: 12, negative: 7 },
  { date: "Dec", positive: 78, neutral: 14, negative: 8 },
];

export const ratingDistribution = [
  { rating: 5, count: 18420, pct: 38.5 },
  { rating: 4, count: 16140, pct: 33.7 },
  { rating: 3, count: 7174, pct: 15.0 },
  { rating: 2, count: 3347, pct: 7.0 },
  { rating: 1, count: 2751, pct: 5.8 },
];

export const platformBreakdown = [
  { platform: "Google Reviews", reviews: 18420, rating: 4.3, sentiment: 80, change: +2 },
  { platform: "TripAdvisor", reviews: 9210, rating: 4.1, sentiment: 74, change: -1 },
  { platform: "Booking.com", reviews: 6847, rating: 4.4, sentiment: 82, change: +3 },
  { platform: "Agoda", reviews: 4124, rating: 4.2, sentiment: 78, change: +1 },
  { platform: "Talabat", reviews: 5231, rating: 3.9, sentiment: 71, change: -3 },
  { platform: "Elmenus", reviews: 2103, rating: 4.0, sentiment: 73, change: 0 },
  { platform: "Facebook", reviews: 1654, rating: 4.5, sentiment: 85, change: +4 },
  { platform: "Instagram", reviews: 243, rating: 4.6, sentiment: 87, change: +2 },
];

export const recentReviews = [
  {
    id: "rev001",
    platform: "Google Reviews",
    platformId: "google",
    rating: 2,
    sentiment: "negative",
    property: "Marriott Cairo — Downtown Branch",
    brand: "Marriott",
    author: "Ahmed Hassan",
    date: "2024-12-15T14:30:00Z",
    text: "The room service was extremely slow — waited over 45 minutes for breakfast. The housekeeping team skipped our room two days in a row. Very disappointed for the price point.",
    department: "Housekeeping",
    isReplied: false,
    isEscalated: true,
    aiSummary: "Guest frustrated with housekeeping failures and slow room service response time.",
    tags: ["Housekeeping", "Room Service", "Slow Response"],
  },
  {
    id: "rev002",
    platform: "TripAdvisor",
    platformId: "tripadvisor",
    rating: 5,
    sentiment: "positive",
    property: "Four Seasons Nile Plaza",
    brand: "Four Seasons",
    author: "Sarah Mitchell",
    date: "2024-12-15T12:00:00Z",
    text: "Absolutely stunning stay. The concierge team, especially Omar, went above and beyond. The rooftop restaurant has the best view in Cairo. Will definitely return.",
    department: "Guest Relations",
    isReplied: true,
    isEscalated: false,
    aiSummary: "Highly positive — praises concierge, rooftop dining, and overall property quality.",
    tags: ["Concierge", "Rooftop", "Guest Experience"],
  },
  {
    id: "rev003",
    platform: "Talabat",
    platformId: "talabat",
    rating: 1,
    sentiment: "negative",
    property: "Cairo Kitchen — Maadi Branch",
    brand: "Cairo Kitchen",
    author: "Mona Khalil",
    date: "2024-12-15T10:15:00Z",
    text: "Order arrived 75 minutes late and completely cold. Wrong items were included. Customer support did not respond. This is completely unacceptable.",
    department: "Delivery",
    isReplied: false,
    isEscalated: true,
    aiSummary: "Critical delivery failure — major delay, wrong items, unresponsive support.",
    tags: ["Delivery", "Wrong Order", "Cold Food", "Critical"],
  },
  {
    id: "rev004",
    platform: "Booking.com",
    platformId: "booking",
    rating: 4,
    sentiment: "positive",
    property: "Sofitel Sharm El Sheikh",
    brand: "Sofitel",
    author: "Jean-Pierre Dumont",
    date: "2024-12-14T18:45:00Z",
    text: "Lovely resort with beautiful beach access. Breakfast buffet was excellent and very diverse. One minor issue — the pool area gets overcrowded on weekends.",
    department: "F&B",
    isReplied: true,
    isEscalated: false,
    aiSummary: "Overall positive — pool capacity concern worth addressing during peak periods.",
    tags: ["Beach", "Breakfast", "Pool"],
  },
  {
    id: "rev005",
    platform: "Google Reviews",
    platformId: "google",
    rating: 3,
    sentiment: "neutral",
    property: "Koshary El Tahrir — Zamalek",
    brand: "Koshary El Tahrir",
    author: "Layla Ibrahim",
    date: "2024-12-14T16:30:00Z",
    text: "Food is authentic as always. But the seating area needs serious renovation — chairs are uncomfortable and the air conditioning was not working properly.",
    department: "Kitchen",
    isReplied: false,
    isEscalated: false,
    aiSummary: "Mixed feedback — food quality praised but infrastructure concerns flagged.",
    tags: ["Food Quality", "Ambience", "Infrastructure"],
  },
  {
    id: "rev006",
    platform: "Agoda",
    platformId: "agoda",
    rating: 5,
    sentiment: "positive",
    property: "Hilton Hurghada Plaza",
    brand: "Hilton",
    author: "Wang Fang",
    date: "2024-12-14T09:00:00Z",
    text: "Perfect holiday! The dive center staff were professional and welcoming. Room was spacious and clean. Dinner at the seaside restaurant was memorable.",
    department: "Guest Relations",
    isReplied: true,
    isEscalated: false,
    aiSummary: "Exceptional guest experience — highlights diving program and F&B as key differentiators.",
    tags: ["Diving", "Room Quality", "F&B"],
  },
];

export const alerts = [
  {
    id: "alt001",
    type: "critical",
    title: "Spike in 1-Star Reviews — Cairo Kitchen Maadi",
    description: "7 negative reviews in the last 3 hours mentioning delivery delays and wrong orders",
    property: "Cairo Kitchen — Maadi Branch",
    brand: "Cairo Kitchen",
    department: "Delivery",
    platform: "Talabat",
    time: "23 minutes ago",
    isRead: false,
    confidence: 96,
    predictedImpact: "Rating drop from 3.9 → 3.4 if unresolved within 48h",
  },
  {
    id: "alt002",
    type: "warning",
    title: "Recurring Housekeeping Complaints — Sofitel Sharm",
    description: "Housekeeping issues mentioned in 18% of reviews over the last 7 days (above 5% threshold)",
    property: "Sofitel Sharm El Sheikh",
    brand: "Sofitel",
    department: "Housekeeping",
    platform: "Booking.com",
    time: "2 hours ago",
    isRead: false,
    confidence: 87,
    predictedImpact: "Booking.com Cleanliness score at risk of dropping below 8.0",
  },
  {
    id: "alt003",
    type: "warning",
    title: "Response Rate Below Threshold — Marriott Downtown",
    description: "Response rate dropped to 34% this week (target: 70%)",
    property: "Marriott Cairo — Downtown Branch",
    brand: "Marriott",
    department: "Guest Relations",
    platform: "All Platforms",
    time: "4 hours ago",
    isRead: false,
    confidence: 99,
    predictedImpact: "Response rate impacts TripAdvisor Popularity Index",
  },
  {
    id: "alt004",
    type: "info",
    title: "Positive Surge — Four Seasons Nile Plaza",
    description: "15% increase in 5-star reviews over the past week — identify and share best practices",
    property: "Four Seasons Nile Plaza",
    brand: "Four Seasons",
    department: "Guest Relations",
    platform: "TripAdvisor",
    time: "6 hours ago",
    isRead: true,
    confidence: 91,
    predictedImpact: "Projected TripAdvisor ranking improvement by 3 positions",
  },
  {
    id: "alt005",
    type: "critical",
    title: "Food Safety Concern Mentioned — Hilton Hurghada",
    description: "2 reviews used terms related to food safety — immediate kitchen inspection recommended",
    property: "Hilton Hurghada Plaza",
    brand: "Hilton",
    department: "Kitchen",
    platform: "Google Reviews",
    time: "8 hours ago",
    isRead: false,
    confidence: 78,
    predictedImpact: "High reputational risk — potential viral amplification",
  },
];

export const brands = [
  {
    id: "br001",
    name: "Marriott",
    type: "Hotel",
    properties: 8,
    reviews: 12430,
    rating: 4.3,
    sentiment: 81,
    trend: +2,
    logoColor: "#C0392B",
  },
  {
    id: "br002",
    name: "Four Seasons",
    type: "Hotel",
    properties: 3,
    reviews: 7821,
    rating: 4.7,
    sentiment: 89,
    trend: +1,
    logoColor: "#1A1A1A",
  },
  {
    id: "br003",
    name: "Sofitel",
    type: "Resort",
    properties: 4,
    reviews: 6234,
    rating: 4.1,
    sentiment: 75,
    trend: -2,
    logoColor: "#2C3E7A",
  },
  {
    id: "br004",
    name: "Hilton",
    type: "Hotel",
    properties: 7,
    reviews: 9102,
    rating: 4.2,
    sentiment: 78,
    trend: +3,
    logoColor: "#003580",
  },
  {
    id: "br005",
    name: "Cairo Kitchen",
    type: "Restaurant",
    properties: 12,
    reviews: 8341,
    rating: 3.9,
    sentiment: 67,
    trend: -5,
    logoColor: "#D97542",
  },
  {
    id: "br006",
    name: "Koshary El Tahrir",
    type: "Restaurant",
    properties: 4,
    reviews: 3904,
    rating: 4.4,
    sentiment: 83,
    trend: +4,
    logoColor: "#E63946",
  },
];

export const properties = [
  {
    id: "pr001",
    name: "Marriott Cairo — Downtown Branch",
    brand: "Marriott",
    type: "Hotel",
    city: "Cairo",
    reviews: 2104,
    rating: 4.1,
    sentiment: 76,
    trend: -1,
    alertCount: 2,
    responseRate: 34,
  },
  {
    id: "pr002",
    name: "Four Seasons Nile Plaza",
    brand: "Four Seasons",
    type: "Hotel",
    city: "Cairo",
    reviews: 4231,
    rating: 4.8,
    sentiment: 91,
    trend: +3,
    alertCount: 0,
    responseRate: 92,
  },
  {
    id: "pr003",
    name: "Sofitel Sharm El Sheikh",
    brand: "Sofitel",
    type: "Resort",
    city: "Sharm El Sheikh",
    reviews: 3102,
    rating: 4.2,
    sentiment: 78,
    trend: -2,
    alertCount: 1,
    responseRate: 58,
  },
  {
    id: "pr004",
    name: "Hilton Hurghada Plaza",
    brand: "Hilton",
    type: "Hotel",
    city: "Hurghada",
    reviews: 2893,
    rating: 4.4,
    sentiment: 82,
    trend: +2,
    alertCount: 1,
    responseRate: 74,
  },
  {
    id: "pr005",
    name: "Cairo Kitchen — Maadi Branch",
    brand: "Cairo Kitchen",
    type: "Restaurant",
    city: "Cairo",
    reviews: 1842,
    rating: 3.7,
    sentiment: 61,
    trend: -8,
    alertCount: 3,
    responseRate: 22,
  },
  {
    id: "pr006",
    name: "Koshary El Tahrir — Zamalek",
    brand: "Koshary El Tahrir",
    type: "Restaurant",
    city: "Cairo",
    reviews: 1204,
    rating: 4.5,
    sentiment: 86,
    trend: +5,
    alertCount: 0,
    responseRate: 88,
  },
];

export const departments = [
  {
    id: "dep001",
    name: "Front Office",
    type: "hotel",
    mentions: 4231,
    sentiment: 79,
    topIssues: ["Check-in speed", "Queue management"],
    trend: +2,
  },
  {
    id: "dep002",
    name: "Housekeeping",
    type: "hotel",
    mentions: 6102,
    sentiment: 64,
    topIssues: ["Room cleanliness", "Towel replenishment", "Minibar restocking"],
    trend: -6,
  },
  {
    id: "dep003",
    name: "F&B — Restaurant",
    type: "both",
    mentions: 9834,
    sentiment: 82,
    topIssues: ["Menu variety", "Waiting time"],
    trend: +4,
  },
  {
    id: "dep004",
    name: "Kitchen",
    type: "both",
    mentions: 7210,
    sentiment: 75,
    topIssues: ["Food temperature", "Portion size", "Allergy handling"],
    trend: -1,
  },
  {
    id: "dep005",
    name: "Delivery",
    type: "restaurant",
    mentions: 5342,
    sentiment: 58,
    topIssues: ["Delivery time", "Order accuracy", "Packaging"],
    trend: -12,
  },
  {
    id: "dep006",
    name: "Guest Relations",
    type: "hotel",
    mentions: 3201,
    sentiment: 88,
    topIssues: [],
    trend: +8,
  },
];

export const topIssues = [
  { issue: "Delivery delays", count: 1842, category: "Delivery", severity: "critical", trend: +23 },
  { issue: "Housekeeping quality", count: 1203, category: "Housekeeping", severity: "warning", trend: +15 },
  { issue: "Wi-Fi connectivity", count: 891, category: "Technology", severity: "warning", trend: +8 },
  { issue: "Food temperature on delivery", count: 734, category: "Kitchen", severity: "warning", trend: +19 },
  { issue: "Check-in wait time", count: 612, category: "Front Office", severity: "info", trend: -4 },
  { issue: "Staff responsiveness", count: 498, category: "Guest Relations", severity: "info", trend: -12 },
  { issue: "Air conditioning issues", count: 421, category: "Engineering", severity: "info", trend: +2 },
];

export const weeklyReviewVolume = [
  { day: "Mon", reviews: 312, responses: 198 },
  { day: "Tue", reviews: 287, responses: 201 },
  { day: "Wed", reviews: 401, responses: 284 },
  { day: "Thu", reviews: 356, responses: 267 },
  { day: "Fri", reviews: 489, responses: 312 },
  { day: "Sat", reviews: 534, responses: 398 },
  { day: "Sun", reviews: 421, responses: 289 },
];

export const aiInsights = [
  {
    id: "ai001",
    type: "prediction",
    confidence: 92,
    title: "Housekeeping Score Drop Predicted",
    description: "Based on the last 72 hours of review patterns at Sofitel Sharm, SEET predicts a 0.4-point drop in the Cleanliness score on Booking.com within the next 5 days unless corrective action is taken.",
    action: "Alert Housekeeping Manager",
    property: "Sofitel Sharm El Sheikh",
    severity: "warning",
  },
  {
    id: "ai002",
    type: "recommendation",
    confidence: 88,
    title: "Replicate Four Seasons Check-in Strategy",
    description: "Four Seasons Nile Plaza's check-in CSAT improved 18% after deploying a dedicated welcome ambassador. 4 other Marriott properties share similar pain points.",
    action: "View Strategy Details",
    property: "Marriott Cairo — Downtown",
    severity: "info",
  },
  {
    id: "ai003",
    type: "risk",
    confidence: 95,
    title: "Delivery Partner Causing Systemic Issues",
    description: "73% of negative Talabat reviews for Cairo Kitchen mention 'driver' or 'delivery partner'. Issue appears systemic, not kitchen-related. Consider switching to direct delivery.",
    action: "View Full Analysis",
    property: "Cairo Kitchen — Maadi",
    severity: "critical",
  },
  {
    id: "ai004",
    type: "opportunity",
    confidence: 84,
    title: "Breakfast Upsell Opportunity — Hilton Hurghada",
    description: "41% of 4-star reviews at Hilton Hurghada specifically praise the breakfast experience. SEET recommends featuring breakfast prominently in Booking.com listing to drive conversions.",
    action: "Create Content Brief",
    property: "Hilton Hurghada Plaza",
    severity: "success",
  },
];

export const benchmarkData = [
  {
    property: "Four Seasons Nile Plaza",
    brand: "Four Seasons",
    rating: 4.8,
    sentiment: 91,
    responseRate: 92,
    reviewVolume: 4231,
  },
  {
    property: "Hilton Hurghada Plaza",
    brand: "Hilton",
    rating: 4.4,
    sentiment: 82,
    responseRate: 74,
    reviewVolume: 2893,
  },
  {
    property: "Sofitel Sharm El Sheikh",
    brand: "Sofitel",
    rating: 4.2,
    sentiment: 78,
    responseRate: 58,
    reviewVolume: 3102,
  },
  {
    property: "Marriott Cairo — Downtown",
    brand: "Marriott",
    rating: 4.1,
    sentiment: 76,
    responseRate: 34,
    reviewVolume: 2104,
  },
  {
    property: "Koshary El Tahrir — Zamalek",
    brand: "Koshary",
    rating: 4.5,
    sentiment: 86,
    responseRate: 88,
    reviewVolume: 1204,
  },
  {
    property: "Cairo Kitchen — Maadi",
    brand: "Cairo Kitchen",
    rating: 3.7,
    sentiment: 61,
    responseRate: 22,
    reviewVolume: 1842,
  },
];

export const monthlyTrend = [
  { month: "Jul", rating: 4.0, reviews: 1821 },
  { month: "Aug", rating: 4.1, reviews: 2103 },
  { month: "Sep", rating: 4.0, reviews: 1987 },
  { month: "Oct", rating: 4.2, reviews: 2341 },
  { month: "Nov", rating: 4.2, reviews: 2289 },
  { month: "Dec", rating: 4.2, reviews: 2419 },
];

export const topPositiveTopics = [
  { topic: "Pool & Beach", count: 3420, pct: 71 },
  { topic: "Breakfast Quality", count: 2983, pct: 62 },
  { topic: "Staff Friendliness", count: 2741, pct: 57 },
  { topic: "Room Comfort", count: 2234, pct: 46 },
  { topic: "Location", count: 2102, pct: 44 },
  { topic: "Check-in Experience", count: 1823, pct: 38 },
];

export const topNegativeTopics = [
  { topic: "Delivery Delays", count: 1842, pct: 38 },
  { topic: "Housekeeping", count: 1203, pct: 25 },
  { topic: "Wi-Fi Quality", count: 891, pct: 18 },
  { topic: "Food Temperature", count: 734, pct: 15 },
  { topic: "Noise Levels", count: 612, pct: 13 },
  { topic: "Parking Availability", count: 421, pct: 9 },
];

export const demoRequests = [
  {
    id: "demo001",
    name: "Karim El-Masry",
    title: "VP Operations",
    company: "Accor Hotels Egypt",
    email: "karim.elmasry@accor.com",
    phone: "+20 100 234 5678",
    properties: "12",
    brands: "3",
    date: "2024-12-15",
    status: "pending",
    source: "Website",
  },
  {
    id: "demo002",
    name: "Nadia Farouk",
    title: "CEO",
    company: "Maison Boutique Hotels",
    email: "nadia@maisonhotels.eg",
    phone: "+20 112 345 6789",
    properties: "4",
    brands: "2",
    date: "2024-12-14",
    status: "scheduled",
    source: "LinkedIn",
  },
  {
    id: "demo003",
    name: "Omar Sherif",
    title: "Director of Marketing",
    company: "Red Sea Resorts Group",
    email: "o.sherif@redsearesorts.com",
    phone: "+20 122 456 7890",
    properties: "7",
    brands: "4",
    date: "2024-12-13",
    status: "completed",
    source: "Referral",
  },
];

export const organizations = [
  {
    id: "org001",
    name: "Marriott Egypt Group",
    plan: "Enterprise",
    properties: 8,
    brands: 2,
    users: 34,
    status: "active",
    joinedDate: "2024-01-15",
    monthlyReviews: 4231,
  },
  {
    id: "org002",
    name: "Red Sea Resorts Group",
    plan: "Professional",
    properties: 7,
    brands: 4,
    users: 18,
    status: "active",
    joinedDate: "2024-03-22",
    monthlyReviews: 2891,
  },
  {
    id: "org003",
    name: "Cairo F&B Holdings",
    plan: "Starter",
    properties: 12,
    brands: 3,
    users: 9,
    status: "trial",
    joinedDate: "2024-11-01",
    monthlyReviews: 1203,
  },
];

export const testimonials = [
  {
    name: "Karim El-Masry",
    title: "VP Operations, Accor Hotels Egypt",
    photo: null,
    initials: "KE",
    text: "SEET has completely transformed how we manage reputation across our portfolio. The AI-predicted alerts saved us from a PR crisis at our Sharm property before it reached social media. Exceptional product.",
    rating: 5,
    brand: "Accor Hotels",
  },
  {
    name: "Nadia Farouk",
    title: "CEO, Maison Boutique Hotels",
    photo: null,
    initials: "NF",
    text: "As a boutique hotel group, we couldn't afford a dedicated reputation team. SEET's AI does the heavy lifting — it reads every review, routes every issue, and tells us exactly what to fix first. Game changer.",
    rating: 5,
    brand: "Maison Hotels",
  },
  {
    name: "Youssef Barakat",
    title: "F&B Director, Kempinski Nile",
    photo: null,
    initials: "YB",
    text: "The Arabic sentiment analysis is unmatched. Other tools miss the nuance in Egyptian Arabic reviews. SEET reads Colloquial Arabic, understands sarcasm, and categorizes it perfectly.",
    rating: 5,
    brand: "Kempinski",
  },
];

export const faqs = [
  {
    q: "Which platforms does SEET monitor?",
    a: "SEET monitors Google Reviews, TripAdvisor, Booking.com, Agoda, Expedia, Talabat, Elmenus, Facebook, Instagram, and other public sources. New platforms are continuously added.",
  },
  {
    q: "Does SEET work for restaurants and hotels?",
    a: "Yes. SEET is designed for the full hospitality spectrum — restaurant groups, café chains, hotel brands, resorts, and multi-brand organizations. Every feature works across both dine-in and accommodation contexts.",
  },
  {
    q: "How does the AI analyze Arabic reviews?",
    a: "SEET's Arabic NLP engine is trained specifically on Egyptian Arabic (Masri) and other MENA dialects. It understands colloquial expressions, sarcasm, and dialect-specific sentiment cues that generic AI tools miss.",
  },
  {
    q: "Can SEET automatically respond to reviews?",
    a: "SEET generates intelligent Smart Reply suggestions for every review, which your team can approve and post with one click. Full auto-reply is available on Enterprise plan with human oversight controls.",
  },
  {
    q: "How does predictive analytics work?",
    a: "SEET's AI monitors patterns across review volume, sentiment trajectories, and operational signals to predict reputation risks before they escalate — typically 3–7 days ahead of a rating drop.",
  },
  {
    q: "Is SEET compliant with GDPR and Egyptian data regulations?",
    a: "Yes. SEET only processes publicly available review data. No guest personal data is stored beyond what is publicly visible. We comply with GDPR and applicable Egyptian data protection frameworks.",
  },
];
